package test.pojo;

public class DeptManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_manager.dept_id
     *
     * @mbggenerated
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_manager.dept_name
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbggenerated
     */
    public DeptManager(String deptId, String deptName) {
        this.deptId = deptId;
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbggenerated
     */
    public DeptManager() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_manager.dept_id
     *
     * @return the value of dept_manager.dept_id
     *
     * @mbggenerated
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_manager.dept_id
     *
     * @param deptId the value for dept_manager.dept_id
     *
     * @mbggenerated
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_manager.dept_name
     *
     * @return the value of dept_manager.dept_name
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_manager.dept_name
     *
     * @param deptName the value for dept_manager.dept_name
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}