package test.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import test.pojo.DeptManager;
import test.pojo.DeptManagerExample;

public interface DeptManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbggenerated
     */
    @SelectProvider(type=DeptManagerSqlProvider.class, method="countByExample")
    int countByExample(DeptManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbggenerated
     */
    @DeleteProvider(type=DeptManagerSqlProvider.class, method="deleteByExample")
    int deleteByExample(DeptManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbggenerated
     */
    @Delete({
        "delete from dept_manager",
        "where dept_id = #{deptId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbggenerated
     */
    @Insert({
        "insert into dept_manager (dept_id, dept_name)",
        "values (#{deptId,jdbcType=VARCHAR}, #{deptName,jdbcType=VARCHAR})"
    })
    int insert(DeptManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbggenerated
     */
    @InsertProvider(type=DeptManagerSqlProvider.class, method="insertSelective")
    int insertSelective(DeptManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbggenerated
     */
    @SelectProvider(type=DeptManagerSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="dept_id", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="dept_name", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<DeptManager> selectByExample(DeptManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "dept_id, dept_name",
        "from dept_manager",
        "where dept_id = #{deptId,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="dept_id", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="dept_name", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    DeptManager selectByPrimaryKey(String deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbggenerated
     */
    @UpdateProvider(type=DeptManagerSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") DeptManager record, @Param("example") DeptManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbggenerated
     */
    @UpdateProvider(type=DeptManagerSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") DeptManager record, @Param("example") DeptManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbggenerated
     */
    @UpdateProvider(type=DeptManagerSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(DeptManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbggenerated
     */
    @Update({
        "update dept_manager",
        "set dept_name = #{deptName,jdbcType=VARCHAR}",
        "where dept_id = #{deptId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(DeptManager record);
}